version: '3.8'

services:
  app:
    image: background-remover
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=True
    volumes:
      - ./models:/app/models

volumes:
  models:
