version: '3.8'

services:
  app:
    image: background-remover
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - HOST=localhost
      - PORT=5000
      - DEBUG=True
    volumes:
      - model_data:/app/models

volumes:
  model_data:
