version: '3.8'

services:
  app:
    image: background-remover
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=5000
      - NVIDIA_VISIBLE_DEVICES=all     # 모든 GPU 사용
      - NVIDIA_DRIVER_CAPABILITIES=all # 모든 GPU 기능 사용
      - MODELS_DIR=/app/models         # 모델 디렉토리 경로
      - PYTHONPATH=/app                # Python 모듈 경로
    volumes:
      - ./models:/app/models           # 모델 디렉토리만 볼륨으로 마운트
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia           # NVIDIA GPU 사용
              count: 1                 # 최소 1개의 GPU를 예약
              capabilities: [gpu]      # GPU 계산 기능 사용
    runtime: nvidia                    # Docker 컨테이너가 NVIDIA 런타임을 사용하도록 지정
